version: "1"
services:
  mariadb:
    image: docker.io/library/mariadb:latest
    hostname: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: slurm_acct_db
      MARIADB_USER: slurm
      MARIADB_PASSWORD: password
      TZ: "Europe/Paris"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - slurm

  slurm:
    image: slurm:latest
    hostname: slurm
    container_name: slurm
    privileged: true
    volumes:
      - munge:/etc/munge
      - slurm_log:/var/log/slurm
      - slurm_data:/var/lib/slurm
      - slurm_statesaveloc:/var/spool/SLURM
      - nhc:/etc/nhc
      - ./config/slurm:/etc/slurm
      - ./home:/home
      - workdir:/workdir
    expose:
      - "6819"
    depends_on:
      - mariadb
    networks:
      - slurm

  c1:
    image: slurm:latest
    hostname: c1
    container_name: c1
    privileged: true
    volumes:
      - munge:/etc/munge
      - slurm_log:/var/log/slurm
      - slurm_data:/var/lib/slurm
      - nhc:/etc/nhc
      - ./config/slurm:/etc/slurm
      - ./home:/home
      - workdir:/workdir
    expose:
      - "6817"
    depends_on:
      - "slurm"
    networks:
      - slurm

  c2:
    image: slurm:latest
    hostname: c2
    container_name: c2
    privileged: true
    volumes:
      - munge:/etc/munge
      - slurm_log:/var/log/slurm
      - slurm_data:/var/lib/slurm
      - nhc:/etc/nhc
      - ./config/slurm:/etc/slurm
      - ./home:/home
      - workdir:/workdir
    expose:
      - "6818"
    depends_on:
      - "slurm"
    networks:
      - slurm

  c3:
    image: slurm:latest
    hostname: c3
    container_name: c3
    privileged: true
    volumes:
      - munge:/etc/munge
      - slurm_log:/var/log/slurm
      - slurm_data:/var/lib/slurm
      - nhc:/etc/nhc
      - ./config/slurm:/etc/slurm
      - ./home:/home
      - workdir:/workdir
    expose:
      - "6818"
    depends_on:
      - "slurm"
    networks:
      - slurm

  login:
    image: slurm:latest
    hostname: login
    container_name: login
    privileged: true
    volumes:
      - munge:/etc/munge
      - slurm_log:/var/log/slurm
      - slurm_data:/var/lib/slurm
      - ./config/slurm:/etc/slurm
      - ./home:/home
      - workdir:/workdir
    expose:
      - "6818"
    depends_on:
      - "slurm"
    networks:
      - slurm
  
  elasticsearch:
    image: docker.io/library/elasticsearch:8.17.3
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - slurm
 
  logstash:
    image: docker.io/library/logstash:8.17.3
    hostname: logstash
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - slurm_log:/var/log/slurm:ro
    ports:
      - "50000:50000/udp"
    depends_on:
      - elasticsearch
    networks:
      - slurm

  kibana:
    image: docker.io/library/kibana:8.17.3
    hostname: kibana
    container_name: kibana
    volumes:
      - slurm_log:/var/log/slurm:ro
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - slurm

  grafana:
    image: docker.io/grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    volumes:
      - slurm_log:/var/log/slurm:ro
    depends_on:
      - elasticsearch
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/graphana
    depends_on:
      - elasticsearch
    networks:
      - slurm
        
networks:
  slurm:
    driver: bridge

volumes:
  mysql:
  munge:
  slurm_log:
  slurm_data:
  slurm_statesaveloc:
  nhc:
  home:
  workdir:
  elasticsearch_data:
  grafana_data:

